### ISSUE TITLE
??

### ISSUE THREAD

**Issue by imllawei** [cgoxopx/ryQr-maker#1]
This idea is very good,but how to get guid?

**Comment by cgoxopx** [comment]
https://github.com/chainsx/myi-killer/blob/master/Unlock/unlock-main.java#L35  
https://github.com/chainsx/myi-killer/blob/master/Login/LoginActivity.java

**Comment by imllawei** [comment]
@cgoxopx thanks for your aid，i have built the two-dimension code that can unlock myipad.
